"""Added Foreign key references

Revision ID: 7b25d1f5e2df
Revises: 5160bd419c9c
Create Date: 2022-08-06 14:18:45.765477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b25d1f5e2df'
down_revision = '5160bd419c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
